### ISSUE TITLE
Interesting! 

### ISSUE THREAD

**Issue by zulfadlizainal** [somidad/telecom#8]
Hi. I saw your website. Could you teach me how to do this interactive graph like you show in https://telecom.jeon.engineer/#/graph ? I also using markdown to host my own website in github pages, and I would like to do the same graph if you dont mind teaching me :) Thank you.

**Comment by somidad** [comment]
I am using [Logseq](https://github.com/logseq/logseq) for note taking. And it provides [GitHub action for publishing](https://github.com/logseq/publish-spa) your notes.

There are alternatives to Logseq, for example, Obsidian (but it's closed source and its publishing service is paid plan only). I believe there are free or open sourced publishing tools (but I did not do a good amount research for it)

**Comment by zulfadlizainal** [comment]
I see! Thank you. I am currently using Docsify. But I am interested in the interactive graph you made. Let me read Loqseq and see whether i can implement inly the graph for my pages :)

**Comment by zulfadlizainal** [comment]
Hi. I have implemented the knowledge graph in my docs page. Thank you for your advice! I use this repo https://github.com/vasturiano/force-graph . 

![image](https://github.com/somidad/telecom/assets/50709439/950b1f47-0fc4-49a3-9e5a-9b8aa26afe0b)
